[package]
name = "bitpack"
version = "0.2.0"
authors = ["quininer kel <quininer@live.com>"]
description = "Rust bitpack library."
repository = "https://github.com/quininer/bitpack"
license = "MIT"

[dependencies]
